
/*
The sequence of triangle numbers is generated by adding the natural numbers. So
the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten
terms would be:

1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

     1: 1
     3: 1,3
     6: 1,2,3,6
    10: 1,2,5,10
    15: 1,3,5,15
    21: 1,3,7,21
    28: 1,2,4,7,14,28

We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five hundred
divisors?
*/

#include <stdio.h>

int triangle(int);
int no_of_divisors(int);

int main() {
  int i = 1;
  while (1) {
    if (no_of_divisors(triangle(i)) > 500) {
      printf("%d\n", triangle(i));
      break;
    }
    i++;
  }
}

// returns triangle number for a given index
int triangle(int n) { return (n * (n + 1)) / 2; }


int no_of_divisors(int n) {
  int no_of_divisors = 0;
  int i;
  for (i = 1; i * i < n; i++) {
    if (n % i == 0) no_of_divisors++;
  }

  // Include divisors which are n/previously considered divisors
  no_of_divisors *= 2;

  // check if n is perfect square, only count once if it is the case
  for (; i * i <= n; i++) {
    if (i * i == n) no_of_divisors++;
  }

  return no_of_divisors;
}